#!/usr/bin/env node
/**
 * Setup pre-commit hooks
 * Run: node scripts/setup-hooks.mjs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const hookContent = `#!/bin/sh
# Pre-commit hook — Kết Nối Muôn Nơi
# Auto-generated by scripts/setup-hooks.mjs

echo "Running pre-commit checks..."

# Stash unstaged changes
stashName="pre-commit-$(date +%s)"
git stash push -q --include-untracked -m "$stashName"

cd $(dirname "$0")/../..

# Run checks
npm run precommit
EXIT_CODE=$?

# Restore stash
if git stash list | grep -q "$stashName"; then
  git stash pop -q
fi

if [ $EXIT_CODE -ne 0 ]; then
  echo "Pre-commit checks failed. Fix issues before committing."
  exit 1
fi

echo "Pre-commit checks passed."
exit 0
`;

const hooksDir = path.join(rootDir, '.git', 'hooks');
const precommitPath = path.join(hooksDir, 'pre-commit');

if (!fs.existsSync(hooksDir)) {
  fs.mkdirSync(hooksDir, { recursive: true });
}

fs.writeFileSync(precommitPath, hookContent);
fs.chmodSync(precommitPath, 0o755);

console.log('✓ Pre-commit hook installed at .git/hooks/pre-commit');
console.log('  Runs: lint + typecheck + security audit');
console.log('  To bypass: git commit --no-verify');
